# frozen_string_literal: true

source "https://rubygems.org"

gem 'capybara'
gem 'cucumber'
#gem 'selenium-webdriver'
gem 'chromedriver-helper'
gem 'report_builder'
gem 'rspec', '3.7.0'
gem 'selenium-webdriver', '3.141'


# gem "rails"
